package CarTest;// Generated by Selenium IDE

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;

import java.io.File;
import java.util.*;
import java.util.concurrent.TimeUnit;

public class EnterRegDetailsTest {
  private static WebDriver driver;
  private Map<String, Object> vars;
  static JavascriptExecutor js;

  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  public void tearDown() {
    driver.quit();
  }

  public static String[] enterRegDetails(String input) {
    String[] output = new String[5];
    output[0] = input;
    driver.get("https://cartaxcheck.co.uk/");
    driver.manage().window().setSize(new Dimension(1160, 702));
    driver.findElement(By.id("vrm-input")).click();
    driver.findElement(By.id("vrm-input")).sendKeys(input);
    driver.findElement(By.cssSelector(".jsx-1164392954")).click();
    js.executeScript("window.scrollTo(0,351)");
    js.executeScript("window.scrollTo(0,1034)");
    driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
    {
      WebElement element = driver.findElement(By.xpath("//dl[2]/dd"));
      String make = element.getText();
      output[1] = make;
    }
    {
      WebElement element = driver.findElement(By.xpath("//dl[3]/dd"));
      String model = element.getText();
      output[2] = model;
    }
    {
      WebElement element = driver.findElement(By.xpath("//dl[4]/dd"));
      String colour = element.getText();
      output[3] = colour;
    }
    {
      WebElement element = driver.findElement(By.xpath("//dl[3]/dd"));
      String year = element.getText();
      output[4] = year;
    }
    return output;
  }
}
